WebFastFoodRestaurantApp/Controllers/OrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using WebFastFoodRestaurantApp.Data;
using WebFastFoodRestaurantApp.Domain;
using WebFastFoodRestaurantApp.Models.Order;

namespace WebFastFoodRestaurantApp.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class OrderController : Controller
    {

        private readonly ApplicationDbContext context;
        public OrderController(ApplicationDbContext context)
        {
            this.context = context;
        }
        // GET: OrderController
        [AllowAnonymous]
        public ActionResult Index()
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = context.Users.SingleOrDefault(u => u.Id == userId);

            List<OrderIndexVM> orders = context
                .Orders
                .Select(x => new OrderIndexVM
                {
                    Id = x.Id,
                    OrderDate = x.OrderDate.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    UserId = x.UserId,
                    User = x.User.UserName,
                    ProductId = x.ProductId,
                    Product = x.Product.ProductName,
                    Picture = x.Product.Picture,
                    Quantity = x.Quantity,
                    Price = x.Price,
                    Discount = x.Discount,
                    TotalPrice = x.TotalPrice,
                }).ToList();
            return View(orders);
        }
        [AllowAnonymous]
        public IActionResult MyOrders(string searchString)
        {
            string currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = this.context.Users.SingleOrDefault(u => u.Id == currentUserId);
            if (user == null)
            {
                return null;
            }
            List<OrderIndexVM> orders = context
                .Orders
                .Where(x => x.UserId == user.Id)
                .Select(x => new OrderIndexVM
                {
                    Id = x.Id,
                    OrderDate = x.OrderDate.ToString("dd-MMM,yyyy hh:mm", CultureInfo.InvariantCulture),
                    UserId = x.UserId,
                    User = x.User.UserName,
                    ProductId = x.ProductId,
                    Product = x.Product.ProductName,
                    Picture = x.Product.Picture,
                    Quantity = x.Quantity,
                    Price = x.Price,
                    Discount = x.Discount,
                    TotalPrice = x.TotalPrice,
                }).ToList();

            if(!String.IsNullOrEmpty(searchString))
            {
                orders = orders.Where(o => o.Product.ToLower().Contains(searchString.ToLower())).ToList();
            }
            return this.View(orders);
        }

        //GET
        [AllowAnonymous]
        public ActionResult Create(int productId, int quantity)
        {
            string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            var user = this.context.Users.SingleOrDefault(u => u.Id == userId);
            var product = this.context.Products.SingleOrDefault(x => x.Id == productId);

            if(user == null || product == null || product.Quantity < quantity)
            {
                return this.RedirectToAction("Index", "Product");
            }
            OrderConfirmVM orderForDb = new OrderConfirmVM
            {
                //Id = x.Id,
                UserId = userId,
                User = user.UserName,
                ProductId = productId,
                ProductName = product.ProductName,
                Picture = product.Picture,

                Quantity = quantity,
                Price = product.Price,
                Discount = product.Discount,
                TotalPrice = quantity * product.Price - quantity * product.Price * product.Discount / 100
            };
            return View(orderForDb);
        }


        // GET: OrderController/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id)
        {
            return View();
        }
        

        // POST: OrderController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Create(OrderConfirmVM bindingModel)
        {
            if (ModelState.IsValid)
            {
                string userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
                var user = context.Users.SingleOrDefault(u => u.Id == userId);
                var product = this.context.Products.SingleOrDefault(x => x.Id == bindingModel.ProductId);

                if (user == null || product == null || bindingModel.Quantity < bindingModel.Quantity || bindingModel.Quantity == 0)
                {
                    return this.RedirectToAction("Index", "Product");
                }
                Order orderForDb = new Order
                {
                    OrderDate = DateTime.UtcNow,
                    ProductId = bindingModel.ProductId,
                    UserId = userId,
                    Quantity = bindingModel.Quantity,
                    Price = product.Price,
                    Discount = product.Discount,
                };
                product.Quantity -= bindingModel.Quantity;
                this.context.Products.Update(product);
                this.context.Orders.Add(orderForDb);
                this.context.SaveChanges();
            }
            return this.RedirectToAction("Index", "Product");
        }

        // GET: OrderController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: OrderController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrderController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrderController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

WebFastFoodRestaurantApp/Controllers/StatisticsController.cs
using WebFastFoodRestaurantApp.Abstraction;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebFastFoodRestaurantApp.Models.Statistics;

namespace WebFastFoodRestaurantApp.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class StatisticsController : Controller
    {
        private readonly IStatisticsService statisticsService;
        public StatisticsController(IStatisticsService statisticsService)
        {
            this.statisticsService = statisticsService;
        }
        // GET: StatisticsController
        public IActionResult Index()
        {
            StatisticsVM statistics = new StatisticsVM();

            statistics.CountClients = statisticsService.CountClients();
            statistics.CountProducts = statisticsService.CountProducts();
            statistics.CountOrders = statisticsService.CountOrders();
            statistics.SumOrders = (int)statisticsService.SumOrders();

            return View(statistics);
        }

        
    }
}

WebFastFoodRestaurantApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebFastFoodRestaurantApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>

<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3 ">
        <img src="/images/Screenshot 2023-03-24 092230-modified.png" width="80" />


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1 topBotomBordersOut">
                <li class="nav-item nav-item-2">
                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>

                <li class="nav-item nav-item-2">
                    <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                </li>
                <li class="nav-item active dropdown dmenu">
                    <div class="dropdown show">

                        <div class="dropdown-menu sm-menu" aria-labelledby="dropdownMenuLinkCategories">
                            <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Salads">Salads</a>                           
                            <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Grilled">Grilled</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Desserts">Deserts</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Product" asp-action="Drinks">Drinks</a>

                        </div>
                    </div>
                    </li>
                <li class="nav-item active">
                    <div class="dropdown show">
                        <a class="nav-link active dropdown-toggle" href="#"
                           id="dropdownMenuLink"
                           data-toggle="dropdown"
                           aria-haspopup="true"
                           aria-expanded="false">
                            Category
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                         
                            <a class="dropdown-item" href="/Product?SearchStringTypeFoodName=&SearchStringCategoryName=Salads">Salads</a>
                            <a class="dropdown-item" href="/Product?SearchStringTypeFoodName=&SearchStringCategoryName=Grilled">Grilled</a>
                            <a class="dropdown-item" href="/Product?SearchStringTypeFoodName=&SearchStringCategoryName=Desserts">Desserts</a>
                            <a class="dropdown-item" href="/Product?SearchStringTypeFoodName=&SearchStringCategoryName=Drinks">Drinks</a>
                        </div>
                    </div>
                </li>
              
        

        @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Client")))
        {
            <li>
                
                <a class="nav-link text-light" asp-area="" asp-controller="Order" asp-action="MyOrders">My Orders</a>
            </li>
        }

        @if ((this.User.Identity.IsAuthenticated) && (this.User.IsInRole("Administrator")))
        {

            <li class="nav-item active dropdown dmenu">
                <div class="dropdown show">
                    <a class="nav-link active dropdown-toggle" href="#"
                       id="dropdownMenuLink navbardrop" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        Statistics Module
                    </a>
                    <div class="dropdown-menu sm-menu" aria-labelledby="dropdownMenuLink">
                        <a class="dropdown-item" asp-controller="Client" asp-action="Index">Clients</a>
                        <a class="dropdown-item" asp-controller="Order" asp-action="Index">Orders</a>
                        <a class="dropdown-item" asp-controller="Statistics" asp-action="Index">Statistics</a>

                    </div>
                </div>
            </li>
        }

        <li class="nav-item nav-item-2">
            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Contacts">Contacts</a>
        </li>
        <li class="nav-item nav-item-2">
            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="AboutUs">About Us</a>
        </li>
        <li class="nav-item nav-item-2">
            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </li>

        </ul>



        <partial name="_LoginPartial" />
        </div>
        

    </nav>
</header>
<div class="container-fluid">
    <!--Add class 'body-container' for 100% width in the page-->
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
@*
<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2023 - WebFastFoodRestaurantApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
*@
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>